<a href="https://colab.research.google.com/github/yuvshan05/numpy_python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myarr=np.array([2,6,5,9,8],np.int8)
myarr

array([2, 6, 5, 9, 8], dtype=int8)

In [ ]:
myarr[1]

6

In [ ]:
myarr=np.array([(2,6,5,9,8)],np.int8)
myarr

array([[2, 6, 5, 9, 8]], dtype=int8)

In [ ]:
#myarr(0) will show error as now my arr contain two element and 1st one is zero look at the brackets
myarr[0,1]

6

In [ ]:
myarr[0,1]=45
myarr

array([[ 2, 45,  5,  9,  8]], dtype=int8)

**array creation:conversion from other python structures **

In [ ]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(listarray)
print(" ")

listarray.size


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 


9

In [ ]:
listarray.dtype


dtype('int64')

In [ ]:
#for zeros
zeros=np.zeros((2,5))
#it will create 2 row and 5 columns
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng=np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
rng.reshape(2,5)#it divide the above array in two eqaul parts

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
lspace=np.linspace(1,50,10)
lspace
#equal differnce between respected elemnets


array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
x=[[1,2,3],[4,5,6],[7,8,0]]
ar=np.array(x)
ar



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [ ]:
ar.sum(axis=0)#sare column ko add kr dega


array([12, 15,  9])

In [ ]:
ar.sum(axis=1)#sare rows ko addkr dega

array([ 6, 15, 15])

mathematic operation through numpy


In [ ]:

ar2=np.array([[12,5,6],[5,35,65],[45,23,78]])
ar2

array([[12,  5,  6],
       [ 5, 35, 65],
       [45, 23, 78]])

In [ ]:
ar+ar2

array([[ 24,  10,  12],
       [ 10,  70, 130],
       [ 90,  46, 156]])

In [ ]:
ar*ar2

array([[ 144,   25,   36],
       [  25, 1225, 4225],
       [2025,  529, 6084]])

In [ ]:
np.sqrt(ar)

array([[3.46410162, 2.23606798, 2.44948974],
       [2.23606798, 5.91607978, 8.06225775],
       [6.70820393, 4.79583152, 8.83176087]])

In [ ]:
ar.max()

78

In [ ]:
np.where(ar>5)

(array([0, 0, 1, 1, 2, 2, 2]), array([0, 2, 1, 2, 0, 1, 2]))

https://docs.scipy.org/doc/
for more information
